name: auto-changelog

on:
    push:
        branches:
            - master
jobs:
    format:
        name: auto-changelog
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - run: git fetch origin +refs/tags/*:refs/tags/*
            - uses: actions/setup-node@v1
              with:
                  node-version: '12.x'
            - run: npm install
            - run: npm run auto-changelog
            - uses: stefanzweifel/git-auto-commit-action@v4.1.1
              with:
                  commit_message: Update CHANGELOG.md
                  commit_options: '--no-verify'
                  branch: ${{ github.head_ref }}
