name: format & lint

env:
    FONTAWESOME_TOKEN: ${{ secrets.FONTAWESOME_TOKEN }}
    NPM_READ_PACKAGES: ${{ secrets.NPM_READ_PACKAGES }}

on:
    pull_request:
    push:
        branches:
            - master
            - develop
jobs:
    lint:
        name: 'lint'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: actions/setup-node@v6
              with:
                  node-version: '18.16.0'
            - run: mv .npmrc.example .npmrc
            - run: npm ci
            - run: npm run lint
    format:
        name: 'format'
        needs: lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: actions/setup-node@v6
              with:
                  node-version: '18.16.0'
            - run: mv .npmrc.example .npmrc
            - run: npm ci
            - run: mv .npmrc .npmrc.example
            - run: npm run format
            - uses: stefanzweifel/git-auto-commit-action@v7.1.0
              with:
                  commit_message: Apply formatting
                  branch: ${{ github.head_ref }}
