name: format & lint

on:
    push:
        branches:
            - feature/auto-changelog
jobs:
    format:
        name: 'Format & lint'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: '10.x'
            - run: npm install
            - run: npm run lint
            - run: npm run format
